### ISSUE TITLE
crash the server after the winner msg

### ISSUE THREAD

**Issue by efor89** [WEATHERCRAFTYT1/BuildBattle#2]
hi

whenever the game ends and the winner is announced, the server crashes.

===BEGIN CRASH DUMP===
eNrtXGtz27i5/iuos3PqnFoy7xd1nIkTO5u0cezGTtOeVSYDkqDENUWyvPiSzv7387wAKJGyk80m
7kw/bGbXEkHgvV9BUP/eSct6xduPV6JusrLYmdl7O222Ejsz0w1dOzQ9O9zbyXnTHtd1We/M/r3T
3la4vSOvj29iUbW0cG9nJZqGL+jWuyIRaVaIhJVp2oh2xizcT7s8f5HlNKFa8nq2v/98tv+uAeL9
I1EUGX00l21Z7Z+V8aVoTwBhcnI2WWVFtuCAPll20X6Vd4usaPafdVmePONtm4vJCuSJekpQ95s6
3n9/fHjx8vjt87eHLy7+eWHuP3uGexWRoNF/Ewysz0ESJGP7BqRU8xgXP+08Mti3AdwlQI9nrJLs
gk0xn3dtljfz+Tv6mM3ESMYveZHkot7NilYsRM2CPda0dVYsfjLDD+weoW/um/4H9tBC32M9IVIg
jNc1v/3Jcj88hqQemYyY3rC238RLkXSgf/+CN5c9L1gKCWzJZj7/EajPBTiqJ0/K4m1XrJm2wtAx
JQbryxjO+6td0w+3pLyeOZ8PiJk8qe9FZG8jUuLYP5MfJ7yA1de7nut8GcuaoMmTFc+Ki2UtePJS
8LqNBG/vwets4z0XNfx014JbbqFSFM3nI5ImT9os3qBt7kHhfg6FeYcbdUfB3JWLvc8sNgH+C4vP
6jJGqChrBcX/HBQ3CD4DpWkhNLU62F69MeNdy7c/A+Djx7gs4Btd3O6W0c8ibtkz3ojniHPN65LD
7PaYHr/HOU+gvdflYkGztIO51gf2fAa/Jc+az5Vr0af0Lejl8841n6+heMZ3QNE+Op9LuYRfkItt
3LFUJXLluAbbNcm+avGvLqvFbh9DjO+LIaN7fVh8vPPhl70d8d2p5cHiOqhRUD5mxVWZX4mVKFqA
TiCJuN3p72JkgATDcZkI4sC0PRM32QP9+2HFb9gBw9/dH6543onm8Z+BDVish8QCRYsCeGQI/9gg
JsXLXcK9x36oYO3tGq39kGjbpWgqoP0hz1ZZO3myEO2uoqVH5zwsuqyZPFEKlMh0pHk8eRLV8PoY
pnKiLG23n1zD2m7Y9OJ4Nvvn8evXp++nbL7z5An+yLHDv707nM53nr179fqIPTu8uHh9zN6/evPm
+O35H/7wB/YDr0XB+8k/vj0+foPZAC5W/PF8p+fS/a/k0jy/mHeGERmzEbdKQWBjzBZZS8+P94D8
dEVDVqGs8CeF/EOPyH9wJ7DueAHc7ifzwx1HCP6LdPbj28N/ksasN0ef15h1V2WKtZ6j8D+sNavH
5BsPrjb7XrVZd9Tmm/9Najt9fURqs99+QW32/WrbCPMhEwGaQcFJelXOb5HfD2X44g2kmD9m/1YI
HzIFSDFWXdHynwUlgqokZelMUOXyyxuUELuPe3adh8bedlXZALfJ/rRlQpou2BAk3uN3Hxp/jeaD
Unz7kb7tmnvM6nF5D49rjMnrMfkPjClLdyVjBweyzwCG4IExaGMMH1pETcWvqRQqxDU7K5uMKtBd
Van8ZHz4E7ja01fmhz9ZZn9hffiTMXX3fsjFlcil22jRBsYDU/jLzi+/bz78vvnw++bD75sPv28+
fO/mw97OQhSi5jn17gWnfe+d0VwQFUE5m/3xHXtqOlPadIgoHu3MzMA093ay5mMirnZmKc8bsbdT
1WVbxiXAOoYPJBntIThp7Eah71s8snnomfiMDNdKYseybdNwkjgyBDcIdqdpeZ8VSXndsDcX7Oj4
/K8Xp2eT07cv/n5+/ldmGlODSRqYGdiexXb7yabxmB2eHKF5BiHLCmD8KagOcfkJYU3yoK9x+2PZ
ECI0rRcYkBfXWSG3NFaojET9Mc+imteZaEhIPFmCsVrs/9yUxQRz9AaJMTWnxtPAcQLD9ww7tIMw
dd0gtUOeGK5rcx4FfhLZaWB6JlFWxjVfZV2zX/H4EhFjokVMBJhTd2o+NRPbsh0rCmJTRPAn146D
IPBjNJim40dObCXc8+2Y+NjYWpQVvL6V3qLJMs2nIogjz00iM/LDMBAiinw7jEzLSS0eglIR+IAq
ojGomOd5BOomqP+yhLe0SQXaAPOpw0XqRZHlpqGfGFFgGxE3Iif1vMB2IpOHceClcci3AJKP59LH
1yJz4hhiMYQTpAagpDHk5cAwuGUEiQliY89GULPHkPJyISFYgCDcMBJJ5CZYJqKQW57n+HFEgsKH
lXJYXJKk/A6ESdXKPNCsiQmjKBbQWRAZphP4PAIg6IB73Ddcx7fIZIWBvnsEasXbpabGeRqZsRVE
lu0laQBpu4kfGV6cBo5lpmHoWZA6jx3TGIMoolZDMAHCNtE7hTAm27aC2Il45HtJbEaBE0PzduyD
YcsQYxA1v4SlKlasafAUWuW+Z6dQg2UlkRHYwnGtIHF4DI2ZdgJnC2zujKE0RVl+Elog1tMAdBsJ
t5PQtmE/cWQLYSUiThNXuI4LIK6fxEm6BaTKJQQHlpKmmBLCOIRjQniwQttDaW/4vunGRhogHgSg
IwCEpIwp3Il9hNKWF222NjmbANmukaSG5QUiNBw39IUdJWHseIEbu7YwhG3bqRCk5tUtLC1q9hMh
KvhodSuBhFP3aWRBO34QisDgoR/BLkzHdNwULIYRGEoCO+a2kPwgSk6yEtotslQ0rbZ9+6nveybM
NIa9Rk7ipKYn/Bj+ZXgJbCaMuWPjfuoMYGzCp6Xcx+WWANWclGnEEE3iurFAERkaHuRj8IinZuSp
EAW5dBRmynof7XOOzJjp2KNBkul6rhekEIYv3AiShrnaHryTC8NO48gUiZtahhdGXwKJ0SiHGgHU
lUDjxLcSO3Ri7odOYjuex214VGyEicu9GGYaePARcQco7WRPatHQFrJSIXkqkp9jppbvWsIJbTh2
6FpehHpHJAEk4KS2Fyae8vVl1VQCWbQuq6WISYNXCGUkf8c1YzsmxQVx6jlGIiwzCE0nNEzhgnPP
ocSyhgJL2tefvXNY4VPkITPhHEEsdCnC2FGIeGNEMWzG4GmcuGYKq+R3gUzw2RVZ2wNDeIV/wpMC
wT3bERzZzHB5EIA8x3cNZAPhm0gMvexHwCjBx+2kRpHYrMl7irhucDfkaerHaeilvptYJnKnE3gG
T7hpCMuNLKHlTtQQwAntwuMPRK6eFgQwNutpzCkgpmmSJBQIDctFAk4t03McDn0kPoKKFyfxFjB6
qDDJ0EZpL7QlMBFxqMu1g9SKAEUYJqJcFMEIEisVtpU4iN5pYm0Bo6cJl6IHYz71rNQLPYR6qNGA
77qmLbxQQCEJkpPnO4lnWUhxW2BacdPiz6rKeSvW3mTEXhhHkJObuLYJr0YgsBxuu5ZrhwgbDrcQ
u4xwG1i2khS5AGI8jYzECMJEGIYZcc9IU1i6sGGdtkDgNRF7DMR/GadGQMCW1KLgK6pxlJA8M3ZD
W4Q+kiHcA36JLGLEyLcxDxKPI2hy09lSnzaqEK7iPuVQS+yK2OZIsohUthUGAWIcPMhKQng3PMew
bDKpBjppECyLfal/DUbFqsRzDQSVyExFLMjPIFjBBf7AbxENfLCG8onfDwYeTJFLTPKyvOyqtcBj
OI9pG6khAs8LUboh5FlG5JuGyQPkvzi2Qk9F0SHUVcV7Y1JyQqZOAlekCMgJh7eYqeHx1IHvxg5J
Lww4okXgjOAkWZpqCOZTW7iWHbu+l1oAESMxpbZBOheoK1zuxibShR+M+RPFVVaXha7cKNKh2EL1
Y6TgQ1hhbNuJDwcxfZFYNtQuLBQz5DVSZQNAN1VZt6Jek5OYVhpBxW7CQ/iCYSZo9iI3FA6Eww0E
+ZAM0RxBWeRlxHPYkLJpR5kjijWkFT9EdUMlYGAhiHshEj+qQB8ZxgyjAJXNCJJqmyaiQBgeShrs
uSmqqAQFkROCFVcg0EVpGtm2D2C2aaFWDRzXvQ+cThASmtI/TBdebscIQoFlxrHhG3D8wPYDJBuE
dt8LDMThMXG1iDuZBRGhCnLkNXHctiglu6lhughGRkzBKRZejKjgJVQwmRCB42+Ba8qujsWkrIhX
XTmr6IJwC7JM33H9IEiEk/KYC6p9eRqiMnONKLFFbI651Q9fVTZFZeCEluHHXhq4jvARQVAYomIK
nYDHgYAa4FZJMIIwbJJIh4ZjmlGCkgfFm/BQSFmRHcZW6qCGQ0XLkXFQ44fSpm5XaVncomnMbxF4
80msyaGk54MlSySJD3FHKMMQPEG/QJZD/RAhgwapmXooI1DUARbtyAmBHEyhKfuk8y+KqKdwWttL
wZIjTJS0VNkJMCE8VAeGGYoUlsuNlALltYhW5Se0+vso2UXd6goKJTL6NVQSNmIjUgASEiVeN4DA
hAPTdM0kQZ5yzXFFuPk6WVXrLvLpV7eEv6wfTMsu7EVZtvCZYdu6Htrb2eiB2KZKm3ftsqwb2jE8
4S3qW3S+vMroWqqKrkXBo1ygPWzrDi1sIio0i7QE95oybY+GA7SJBPgrAjafpxr3fD6ggvocaqdP
zy/en759faSE2mTSyWkT8zznVSXqAQ/9yJgFd+qMWfi5/LkUPv0b8QGJfjMjjcKs9ld+jfhl21bN
bH8fbf2yi6YI7PsbkvZ7JsDhSZe32fuypn2CNZODwW0+rTGfzz+JeHl2ciSuGtz4e3aTXT7/P3mS
Dv1t011m+H6J1jS7bB5KoTGhrFYJUM7nK6L0miiFXIZU/1bpDBjZHwAiG7i8fc/rZmgDemQsG0Sl
sWykNF4ePRTfVwRuCT6by9trThtgGzp+K7c/8hWHovZ7CGBzeFhkw+r4CMmQXWPba7c2qR+K7Tt7
3+o4zK957o81j57xxYCVfmTIhoX+1x6zAWPt8tvvo37nBdLNRc2LJoWXbXhRsOfzRU2JYfHNrnzS
ZXWaiTzZ75kCx2ddLc5EvRpa6mZsrLw7XHvOixeGwf6HndUlVRSvijRDdXn7UFr8qBDM52uKBl+/
QQJyrX7qsoFDUjiZPBM8LouRGDaD20bsbsVt3pTF9W1RmMZDsT4AOZ9HkgwY8ZqcX7Xkk3N63jdk
px8ZW/JWZD6+KvNzkPRQbGiksNk1dk36+cXh24t3Z/eq7Pr6eipACUGdtpcy0PAEsTV5RrsYo9S6
dWM7uoZj/pquvuKFaBH8Lx+KRwkTSuIJoCaRIgTK2ibsq6xV10JTCXSqKd1/NAZOAvnr6cXLgRjk
5Z1YCwNu+ZaK/8LjS1SSS3xY43jrf7sMRkDnc6Lm6+KUzJW07/6yG9YS66EhSy7tNd1l5uTBkqWC
hhSpsW++fQ0bz7umLVcvXhwO+NiMbRum/fHZ8cXhmJujmi/Kv795KHaA9uuVoCg9zNESNHcY0MPj
0GH+Z0PHEPN8vkXHtwWR50vennQput5hBBmO/kqPcbHs6PG5bduO+1B8DmFSOSoJWX/5pjwvV/af
xPgx0ka5uj08ezXgezA49jJ/OyuUhYjw/0NxrMHN50JRAJjz+YiaXw8Z2arKBarQahg0NoNDhuRe
xJihFzy/zOp7uos9tUvzPYUb9X/l9eDyGH02PfPIm7PjQVmXahpQmku6UZ1XCDhDHr7Sac+XZfXu
1R2n1cPbotiqXc553t6eZTciRxfz6TepeGhBX1D3GEPvyoq6Kwss49vXmDmsvCFQFYGaLnhfvpL/
blWvcmi7eDXN+6rX38bxpmq8zwrkw5YGxTAQ/UNcZWUHlU/68Z3PFLZE7ObbA5S1Egw5yeHzoXfg
aigSe+pNva38w+vL9/zqofxcg4OGD5/LP18O3EQynRM5zHPZRg/T0Hh8u84ZK3a0dWJ9O/mXZZEV
i7gs8/mcyOZ5LvcMmq9Pqs/yTrwVtJc8rFg3g2NGtrqrs5w3K/59FdqO9Dt5XuSiPMoalDPJwA4V
ivlckdN/fg1nR8d/z2pJ+Jqv9dB2qeOP+arKBZ0bgX2evniwnKKAzudXkoT5PBH9twFZv2J80rrg
vS29EbPhazQ8LoHsafDw+wB3O39pdpWiYNv4vlQC3dv8D3Zs+xOIbS3osAMdrdwfcbvZzHxbtnIv
/u6m5vrOr2xsfWZz8zvEs0XAb3DL/hD7uJMcjG5tYP5nK90BYrSNIyq+rc79xzORbO0+roe2K9wt
A/6HKFCpHPFiawf6N4adgdNR8KmpuhkGnhuJJuFyU0MSNp+rM4K/rj96YsBrQIWIVIy7cwhOZmd5
/G5K5wzQNMhTXjuPztZX7HlZpNmC0dPweT0vHp3zlv2ly5nDDG9mOjM7YM/OL5hlWAbdz3mx6PhC
HCSio+tV2SYH9HoD9yNwyxai6eJl+we6p1BPSPQHwLjK6ORtM7hDUfbAcl3PpUGS0KpMxIFEtOI3
E/2awoFlyCF5dnuiAwCkejAxafh6CZFM8qxpD8o0pRGlocm/OlHfHsAjNkM1SjU9Ql+nFW8a2lE4
+F/5b17woii7IhYa94THy0yo1wQbvTAt6bHcmlqNE+JOqEvur6urSs+nB7pZ3KFkO7Akn/JIYlvW
k0a0LXJrcyAlS0fLlbBel1F0a24GGyGSwRx6dHZwdPzi8N3rCxqF3ZaThl8JjfAqE9eTJKPzF7E4
MCXSm6i8mZCB6zmjx1fT2xUdaHrEKHKwWFpEpx46SsOgF0fYyLxgKOyCnsOxngfGa8HapWBoaRp8
gRnFJMyWRYJlRZx3iUjwhd0xSIJ1Xq6wMmXtXZgNT8UeK3Gnbggki2rBL9lt2dUaFstSBlVkCOyE
AVqglzmRMQD4jbheg9tPRMqhh4Zdl8UfW0Zhk9eMxLcCs3Qc8JYopFd5FN/XS1GwrlrUPAGA6bwg
01XAZvOCsUfvl4IIY20JLEXCAEIfuIUMqPehgxyJui1JzUugAav4JlopL0rRsWBLeU6cRlYEWRlZ
720zJg+e0o1m2bVJCT/QL83SS0Xq6DGL87IRyXxHUoYysbxm5BUgpn+JgF1lnP2N3ILmSP/os9+M
UTiTS4+lr+g1jN5fIcNm0BiEQtCiW6ZFSfO1a61vD4h99D6DQMoCcuVJwmoEByl+Eisd12YrwRuU
6uReDEKPBBEN4Yh/dTwnsS2yK8yV78ayXY0UwegxQVcY6RwWBZIJxE7npme4LXG/6VYRpAKrOmxu
i5iOyTPaRoQdTeWEd5CWNO2eU5q2rNHMddAepjd7TNYcTLss/GGP0TkPMEK5Q8oGMZnGVl0BC6Ip
Cvi5VC94gpXV5U0GCxMQA1iSllusiSPZaoJepWSrNIdsco9l7R8hvraWyxJBYU+azNZitgseOviN
JcUi2ZhoTmcS1LatcmkcdVdQaU8WCLlXUgnyxHEzZehR9Xe2yhZLOHPNm+Xe0Pm04ZBE6rqrWjWq
BEaCWYE2zZdULpxSHidOlEPwqzJLQPb9FJCNkM2VEDSsazowNEyeqElrS0O6QDCub5VT/igPnDDK
xUyNM/kGMvn2Six4dNtC4uxcidqQws0agi2XX5DWrjMpeWlRcNrriQLUG1kjOUwzkIiIBOoLCStF
BdmjVEYObXXkpmxRQlF0dE1aBSHS52IkaTNmEBfALkOwOrf7X88BVTFfop9y4vfR37RlJUnQ4XNN
kgbXMIQPSuKIez1BhLWnyjQsRxMmg8B76RWavuaPD0Ch9AtJEkUMFndIPgWSDxM3Iu5k8C0Vycoj
KVmtZ4ubGKm92XCkAtfpxfGMXbx8dc5evzp5dcEOz85evzo+Z2fHbxlKwb8ev91jmMQuTjHrmL1/
efr6mJ29PX1+fH4+3Q4BI3lYrqfFcSZQmMqETIG4IQbjpZAhWUpjHWxNyB4lQSJji5wyQSgUKsxK
UCghwScCNKyJ+P2csSkjQ7lGCbCgaRqZhKyAIPRuArnKSBLHKeUQyvNywfTubLIFXZlDbZWIqRxQ
kiVylV7V2jUPMC9RNRtWbUPz2jy+nyTNua05X/A6olcb4jLXR4xlALpfutLViBy9iulViN0rXnSy
+BhSgsKsgw0+3utzwrYR9mao0muaApbid7VxwSk7VTFfGTyqh7LLkzUtGZLIdcE29DcKcCXJB6Oe
YWhege2FDBZ3kqQ0HQVhzVuKcr9Ptmq1njEZmuZQw8SN1uQd22D3mNTIOs77gpFUVgMTmaE25KRb
Vaq6UiUc0zcmdKPX1xFN0gsk7ZLMngN6RfpawNn5PQJG0kbiA4YrGFnTdIICQ7uE1hZ9tUlBi7Bt
qNrrFalqBF1UThU1NPWzcqK+KF52xWXT0/6cVzSarboVciw9RGF98U+KZKqTUVRs5Er+okUpPeau
jaHYrjRFEuGEquAOSddZa+yoVLe2bZpqI4p6Cr6a3LuQgqUnDjmTlcMkRscl1rwdgRRZq6B8JOmB
OlVgKCj0bpGgRoPWKA433GGZlqfip8dMkzfVLgkwpzZAw/0yqC/Z4bzQz6lnOkWgNFuWuSoxI96i
k6RKXJLc0AuuTCcZGdtU56PvqtQSiXWxqdLbo6GW+lsUVuvbloDvsYk5UKBUnkQ8aXtidAqQUXtT
x8q+kkrIRHFOvYws9GkxBjVZU/YStSBs6UAWd+z52bs9rAUNEfzrOktg9rJWUNFzDX8i4c+Y35fd
m4q8kdIZzJ2ywwSBasnzdB+tpGoTEgEb1qiAlNHWCBnYwBE3aW8AbNiKHN9QVKMSk+d7KmgSav1W
3ZRd1DJflLKSfndWnPV1+KY3pDaDFtEuDsHsqqKa6OutxudEO2STfRJrVVPF3muYHob11RQqemU5
g6zrhJZa9HjKzvSanNcLuYDrJlWbicSY1nxB3NFL2uiMq1wWM9R5rkA8xQFekwqf5xltZshWml7D
FE3LTi7eSUobsERsR13LqHWXWt6gU33HtA9Dq7ab0KqZpJYcIBFRt5j1vcwTZlIPoyu5JbxY3me6
c21Ur01GXjSlymnaUEwCpuKWgvZ8WaK3JePsWxjRN6kyuCW85azhV30Qpd2QfguH7m38nd67QiQQ
vO1jDChVr3X2JbNst6palStNhQpNli9FGedZxeRayPGE30KGZCyr8qrvYCn865gp49akv6dQNpto
0e/sDHcTLuR2gDIA9cONaiNFztXa7hq9LRHD6lsVF/SaiVozYxUKiqssJzQq5ml/1lgoaPNisS6q
C1qWb+eOvX7WaDvp3h0c1eUdrsqObDpVwVmbOIlSbePJZETuLHt3KIa+y2yCxW9lbhkslowXQvWK
kVDAIkE/YcLkRqBMB8veAqTS5f7gKEsp9gnRmn14JuPbpFbqvXFgox9IuY9K434yeQ1IsI/eEEFs
v5g+19TY0rqpk550FSxSNINoEVMCkojkNuZgK+bVkUQmDzw10iVJnqImTTP6BQ6UKpo7pnce+mwn
14xYB7wJs9gjtkDP0mzEs9ndWEtoeldE2lmveSabGgQOVPxKN1VZdXlvjPqCwr6co0OELQOErIYn
lXZriq7kqTPW15lyK1Pt58x0xqPtJ9ljqWGVMLS+QMhmYyDZyI3sXb4ttjW0drfxcLVEaZaWA43A
yybqycJ65rIkzUhSptVqVU2zUlJclMXtinoEesGFttviZkM6NT76PtvclyzIkMUXixrdptpZ0ttQ
qtumnwC53OZP0gcPPj06pXfoJzoIqlxAQeFaqEKUyx84IYyNJHzDgBybDvZ+kXrWklemqZRzR6hQ
qLqvjQlZT77rQrF7WE/J8XIoOpSoBdnJYJtnD/GxWvI9DEMMlLDadclCP6Ik0EZDhYhABSUEdbdP
LGrTiI+2jfTjnEHC6VCeIbfJKNYHCw1Qal7d73Hc0bTidajqFj30OlbrjERAaX5fOJBmKWASQrkf
phf1e5/TDQJ9Z4ihl+aXc54O20q7yisG2wwaBsC3Wp79hsJSD8qIQR2BLjJ1xKD9WdTxiayysnQN
CKU6GFGb8RSB+i5bxTj6uRYVIvvMxvOMN7qER9XF6SSPvqIiADRqXc16pal7sFva7pmxn2T2Rv7c
k/s/HwioOnKwTpPDhwSSDaqk6izRHXb/hEW2zvdlLJnQZYZuZDEpOzN6cwG06nQ7JF/hlTSor4we
yVBWUNlrg3HGXrw+vJhZf/b33PDG3LNv7D3rz+afExGXKsbu0mPmmILrQWCoUKyuHPexKnvUfvyw
sVUeTrkFMtb7TrL0kBtH0Fp8y9RPjnR1H5T7ar5e7+TLiAM4SFWxfFLS9AKb9E8BYAuqvnv0QoYa
iUrOHwGRR/X0yMfByEQWW9PNFlkpf1yIiRsEvkY3QvEl1cuNLPohkShDpXqremY5j/iVb8jnKo0o
n1FcSvgoRup1rN7Z2xE3rSj0b0v8e+c5KoThb2JEsf79gvUIPYEpEl6PxsrVx6RsEQxHo/ottc1A
V+fD60S907i+TrNcvS+5HlmsRr/QsUT6GF5n8LKr4QD97oZ8Ju3Lc3irSD1OGk6hSiyhB8mDsSoe
c/12/db7aKUM+814CAXKajhyfvZ6eLm6bf6Vy58V0d8YvVBsWrQPz1BPGKZrOIaPrz+8gkv4cYz/
Qk94vpt6iW8JN06N1PL81AmE6fkxvQRn2ewHepVv8ArfGuEtl08jLX3u9FNWqWf06j2xT+pHINaz
cXmzGuukJHYsw7BN06KBs6PTkaiS8qNkZXsQQ9lYnQgXRdOMJqqTif84GcloiwJcUks6ZguD13W2
ZR2DX+iw6awI/cgMCF6OjXOTrT/KYmz46yckomyhfhVFvXgoj60mzeDkvwxoSdT/AgfZcX1btaUc
sOXAIrmj82xkJlI29nBo/cLrolPG2JPzf1SznZ7JrZTNgl9++X/bxvZ1
===END CRASH DUMP===

**Comment by WEATHERCRAFTYT1** [comment]
Can you send me the error of the plugin what line did it crashes?

**Comment by efor89** [comment]
Error: Undefined offset: 2
File: plugins/BuildBattle-master.phar/src/WEATHERCRAFTYT1/BB
Line: 1370
Type: ErrorException

**Comment by efor89** [comment]
you need the code or the backtrace too?

**Comment by efor89** [comment]
Error: syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION) or const (T_CONST)
File: plugins/BuildBattle-master.phar/src/WEATHERCRAFTYT1/BB
Line: 223
Type: ParseError



this is the new error

**Comment by WEATHERCRAFTYT1** [comment]
I’m on it.

**Comment by efor89** [comment]
i love bb i hope you can fix it :)

**Comment by WEATHERCRAFTYT1** [comment]
pls send me the zip of the plugin because i updated it long ago on #1

**Comment by WEATHERCRAFTYT1** [comment]
and yes send the backtrace

**Comment by efor89** [comment]
i download the new master convert it and put it in plugin folder

**Comment by efor89** [comment]
this is the backtrace from the old master

Backtrace:
#0 plugins/BuildBattle-master.phar/src/WEATHERCRAFTYT1/BB(1370): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[19] Undefined offset: 2, string[117] phar://C:/Users/Dennis/Desktop/PocketMine-MP-minigames-hub/plugins/BuildBattle-m, integer 1370, array[25])
#1 src/pocketmine/scheduler/TaskHandler(137): WEATHERCRAFTYT1\GameSender->onRun(integer 29941)
#2 src/pocketmine/scheduler/TaskScheduler(179): pocketmine\scheduler\TaskHandler->run(integer 29941)
#3 src/pocketmine/plugin/PluginManager(654): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 29941)
#4 src/pocketmine/Server(2391): pocketmine\plugin\PluginManager->tickSchedulers(integer 29941)
#5 src/pocketmine/Server(2154): pocketmine\Server->tick()
#6 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
#7 src/pocketmine/Server(1588): pocketmine\Server->start()
#8 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[52] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\, string[60] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\plugins\)
#9 src/pocketmine/PocketMine(304): pocketmine\server()
#10 (11): require(string[107] phar://C:/Users/Dennis/Desktop/PocketMine-MP-minigames-hub/PocketMine-MP.phar/sr)

**Comment by efor89** [comment]
and this the new

Backtrace:
#0 vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[18] WEATHERCRAFTYT1\BB)
#1 (): BaseClassLoader->{closure}(string[18] WEATHERCRAFTYT1\BB)
#2 (): spl_autoload_call(string[18] WEATHERCRAFTYT1\BB)
#3 src/pocketmine/plugin/PluginManager(167): class_exists(string[18] WEATHERCRAFTYT1\BB, boolean 1)
#4 src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[83] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\plugins\BuildBattle-master.p, array[2])
#5 src/pocketmine/Server(1531): pocketmine\plugin\PluginManager->loadPlugins(string[60] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\plugins\)
#6 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[52] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\, string[60] C:\Users\Dennis\Desktop\PocketMine-MP-minigames-hub\plugins\)
#7 src/pocketmine/PocketMine(304): pocketmine\server()
#8 (11): require(string[107] phar://C:/Users/Dennis/Desktop/PocketMine-MP-minigames-hub/PocketMine-MP.phar/sr)

**Comment by efor89** [comment]
i delet now the 2. and 3. winner msg in bb.php and it works now

**Comment by WEATHERCRAFTYT1** [comment]
Ok thats fine

**Comment by WEATHERCRAFTYT1** [comment]
Wait what lines did u delete??

**Comment by efor89** [comment]
in the bb.php i have was it 1374-1378

**Comment by efor89** [comment]
i add now a line and i have now 1st 2nd 3rd winner i think you forgot a line 
they 3x 1st winner lines 3x 2nd winner lines and was only 2x 3rd winner lines

**Comment by efor89** [comment]
unset($paints[$quien3]);

i add this line

**Comment by efor89** [comment]
this is wat i have now


$this->plugin->getServer()->broadcastMessage($this->prefix .TE::YELLOW. "1ST°: ".TE::AQUA.$quien." ".TE::GREEN.$max);
unset($paints[$quien]);
$quien2 = array_search($val[1], $paints);
$this->plugin->getServer()->broadcastMessage($this->prefix .TE::GRAY. "2ND°: ".TE::AQUA.$quien2." ".TE::GREEN.$val[1]);
unset($paints[$quien2]);
$quien3 = array_search($val[2], $paints);
$this->plugin->getServer()->broadcastMessage($this->prefix .TE::GOLD. "3RD°: ".TE::AQUA.$quien3." ".TE::GREEN.$val[2]);
unset($paints[$quien3]);

**Comment by efor89** [comment]
this is now working for me

**Comment by WEATHERCRAFTYT1** [comment]
That’s was the exact code I was going to put lol but that’s fine :).
